### ISSUE TITLE
Rewrite music commands with Lavalink

### ISSUE THREAD

**Issue by SKBotNL** [Fossium-Team/FossiumBot#6]

**Comment by SKBotNL** [comment]
Almost done, might add a queue system later

**Comment by ghost** [comment]
> Almost done, might add a queue system later

Please test commit:
`191d845b156e7d77b760482a2173d2f84ade1fc9`

**Comment by ghost** [comment]
Should be working smoothly after commit `69cbf0626fe0b6a328c3849004c4735d7cfbbe9b`

**Comment by SKBotNL** [comment]
Added

**Comment by SKBotNL** [comment]
@odysseus443 please make a playlist command

**Comment by ghost** [comment]
f7a90d938923013d53973053e4f2e2988bb10b11, 81ffcc399ed9d5d94f35572ba69c3657d8ea3854

**Comment by SKBotNL** [comment]
fixed
